/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.Board;
import Control.GameControl;
import Model.CharactersLibrary.Classes.Fighter;
import Model.GameClasses.Configuration;
import Model.GameClasses.Square;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Esteb
 */
public class GameScreen extends javax.swing.JFrame {

    /**
     * Creates new form GameScreen
     */
    
    GameControl admGame;
    public GameScreen(int size, Fighter userFighter) {
        initComponents();
        admGame = new GameControl(size, userFighter, this);
 
        this.jTextFieldCharacterLevel.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setFocusable(true);
        this.jPanelImage.setSize(100, 100);
        this.jPanelItemImage.setSize(100,100);
        this.addKeyListener(admGame);
    }
    
    public void addBoard(Board board){
        
        Square[][] squares = board.getBoard();
        for(int i = 0; i < board.getSize(); i++){
            for(int j = 0; j < board.getSize(); j++){
                Square oneSquare = squares[i][j];
                this.screenBoard.add(oneSquare.getPanel());
            }
        }
    }
     public GameScreen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenBoard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelCharacterTittle = new javax.swing.JLabel();
        jPanelImage = new javax.swing.JPanel();
        jLabelCharacterImage = new javax.swing.JLabel();
        jLabelImageCharacter = new javax.swing.JLabel();
        jTextFieldCharacterLevel = new javax.swing.JTextField();
        jProgressBarExperience = new javax.swing.JProgressBar();
        jlabelCharacterEXP = new javax.swing.JLabel();
        jLabelCharacterName = new javax.swing.JLabel();
        jLabelCharacterhealth = new javax.swing.JLabel();
        jTextFieldCharacterName = new javax.swing.JTextField();
        jTextFieldCharacterSpeed = new javax.swing.JTextField();
        jLabelCharacterSpeed = new javax.swing.JLabel();
        jProgressBarHealth = new javax.swing.JProgressBar();
        jLabelHealth = new javax.swing.JLabel();
        jLabelCharacterLevel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbuttonSalir = new javax.swing.JButton();
        jLabelGameStadisctics = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelItemTitle = new javax.swing.JLabel();
        jLabelItemName = new javax.swing.JLabel();
        jLabelItemLevel = new javax.swing.JLabel();
        jTextFieldItemName = new javax.swing.JTextField();
        jPanelItemImage = new javax.swing.JPanel();
        jLabelItemImage = new javax.swing.JLabel();
        jLabelImageWeapon = new javax.swing.JLabel();
        jTextFieldItemLevel = new javax.swing.JTextField();
        jTextFieldItemDamage = new javax.swing.JTextField();
        jLabelItemDamage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        screenBoard.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout screenBoardLayout = new javax.swing.GroupLayout(screenBoard);
        screenBoard.setLayout(screenBoardLayout);
        screenBoardLayout.setHorizontalGroup(
            screenBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        screenBoardLayout.setVerticalGroup(
            screenBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabelCharacterTittle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCharacterTittle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCharacterTittle.setText("Character");

        jPanelImage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImageLayout = new javax.swing.GroupLayout(jPanelImage);
        jPanelImage.setLayout(jPanelImageLayout);
        jPanelImageLayout.setHorizontalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageLayout.createSequentialGroup()
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelImageLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelCharacterImage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelImageLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelImageCharacter)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelImageLayout.setVerticalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelCharacterImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImageCharacter)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTextFieldCharacterLevel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCharacterLevel.setFocusable(false);
        jTextFieldCharacterLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCharacterLevelActionPerformed(evt);
            }
        });

        jProgressBarExperience.setForeground(new java.awt.Color(0, 204, 204));

        jlabelCharacterEXP.setForeground(new java.awt.Color(0, 255, 255));
        jlabelCharacterEXP.setText("/exp");

        jLabelCharacterName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCharacterName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCharacterName.setText("Name");

        jLabelCharacterhealth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCharacterhealth.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCharacterhealth.setText("Health");

        jTextFieldCharacterName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCharacterName.setFocusable(false);

        jTextFieldCharacterSpeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCharacterSpeed.setFocusable(false);

        jLabelCharacterSpeed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCharacterSpeed.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCharacterSpeed.setText("Speed");

        jProgressBarHealth.setForeground(new java.awt.Color(255, 102, 102));

        jLabelHealth.setForeground(new java.awt.Color(255, 102, 102));
        jLabelHealth.setText("health");

        jLabelCharacterLevel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCharacterLevel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCharacterLevel1.setText("Level");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCharacterhealth)
                            .addComponent(jLabelCharacterName)
                            .addComponent(jLabelCharacterSpeed)
                            .addComponent(jLabelCharacterLevel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jTextFieldCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldCharacterSpeed)
                                        .addComponent(jProgressBarHealth, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                    .addComponent(jTextFieldCharacterLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCharacterTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBarExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabelCharacterEXP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCharacterTittle)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCharacterName)
                            .addComponent(jTextFieldCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCharacterLevel1)
                            .addComponent(jTextFieldCharacterLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCharacterSpeed)
                                    .addComponent(jTextFieldCharacterSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCharacterhealth)
                                        .addComponent(jProgressBarHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelHealth))
                                .addGap(50, 50, 50)
                                .addComponent(jProgressBarExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlabelCharacterEXP)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));

        jbuttonSalir.setBackground(new java.awt.Color(198, 83, 83));
        jbuttonSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbuttonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonSalir.setText("Salir");
        jbuttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSalirActionPerformed(evt);
            }
        });

        jLabelGameStadisctics.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelGameStadisctics.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGameStadisctics.setText("Game ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbuttonSalir)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabelGameStadisctics)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jbuttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabelGameStadisctics)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(20, 86, 152));

        jLabelItemTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelItemTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelItemTitle.setText("Item");

        jLabelItemName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelItemName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelItemName.setText("Name");

        jLabelItemLevel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelItemLevel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelItemLevel.setText("Level");

        jTextFieldItemName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldItemName.setFocusable(false);

        jPanelItemImage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelItemImageLayout = new javax.swing.GroupLayout(jPanelItemImage);
        jPanelItemImage.setLayout(jPanelItemImageLayout);
        jPanelItemImageLayout.setHorizontalGroup(
            jPanelItemImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemImageLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabelImageWeapon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelItemImageLayout.setVerticalGroup(
            jPanelItemImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemImageLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelItemImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImageWeapon)
                    .addComponent(jLabelItemImage))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTextFieldItemLevel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldItemLevel.setFocusable(false);
        jTextFieldItemLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemLevelActionPerformed(evt);
            }
        });

        jTextFieldItemDamage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldItemDamage.setFocusable(false);
        jTextFieldItemDamage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemDamageActionPerformed(evt);
            }
        });

        jLabelItemDamage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelItemDamage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelItemDamage.setText("Damage");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelItemTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelItemName)
                            .addComponent(jLabelItemLevel)
                            .addComponent(jLabelItemDamage))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldItemLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldItemDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelItemTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelItemName)
                            .addComponent(jTextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelItemLevel)
                            .addComponent(jTextFieldItemLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldItemDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelItemDamage))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(screenBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screenBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSalirActionPerformed
        this.admGame.stopGame = true;
        MainScreen ventana = null;
        try {
            ventana = new MainScreen();
        } catch (Exception ex) {
            Logger.getLogger(GameScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbuttonSalirActionPerformed


    private void jTextFieldCharacterLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCharacterLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCharacterLevelActionPerformed

    private void jTextFieldItemLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemLevelActionPerformed

    private void jTextFieldItemDamageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemDamageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemDamageActionPerformed
    public void updateInterface(){
        Fighter fighter = admGame.getBoard().getFighter();
        String fighter_name  = fighter.getName();
        int fighter_level = fighter.getLevel();
        double fighter_health = fighter.getHealth();
        double fighter_speed = fighter.getSpeed();
        double fighter_experience = fighter.getExperience();
        
        String itemName= fighter.getSelectedItem().getName();
        int itemLevel = fighter.getSelectedItem().getLevel();
        double itemDamage = fighter.getSelectedItem().getDamage();
        
        this.jTextFieldCharacterName.setText(fighter_name);
        this.jTextFieldCharacterLevel.setText(String.valueOf(fighter_level));
        this.jTextFieldCharacterSpeed.setText(String.valueOf(fighter_speed));
        
        this.jProgressBarHealth.setValue((int) fighter_health);
        this.jProgressBarExperience.setValue((int) fighter_experience);
        
        this.jTextFieldItemName.setText(itemName);
        this.jTextFieldItemLevel.setText(String.valueOf(itemLevel));
        this.jTextFieldItemDamage.setText(String.valueOf(itemDamage));
        
        paintImage(jPanelImage, fighter.getCurrentTexture(), jLabelCharacterImage);
        paintImage(jPanelItemImage, fighter.getSelectedItem().getCurrentTexture(), jLabelItemImage);
        this.repaint();
    }
    private void paintImage(JPanel panel, String route, JLabel label){
        route = Configuration.IMAGE_ROUTE.concat(route);
        label.setSize(panel.getWidth(), panel.getHeight());
        ImageIcon image = new ImageIcon(route);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(
                                    label.getWidth(), 
                                    label.getHeight(), 
                                    Image.SCALE_DEFAULT));
        label.setBounds(0, 0,    panel.getWidth(),  panel.getHeight());
        label.setIcon(icon);
        panel.add(label);
        panel.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCharacterImage;
    private javax.swing.JLabel jLabelCharacterLevel1;
    private javax.swing.JLabel jLabelCharacterName;
    private javax.swing.JLabel jLabelCharacterSpeed;
    private javax.swing.JLabel jLabelCharacterTittle;
    private javax.swing.JLabel jLabelCharacterhealth;
    private javax.swing.JLabel jLabelGameStadisctics;
    private javax.swing.JLabel jLabelHealth;
    private javax.swing.JLabel jLabelImageCharacter;
    private javax.swing.JLabel jLabelImageWeapon;
    private javax.swing.JLabel jLabelItemDamage;
    private javax.swing.JLabel jLabelItemImage;
    private javax.swing.JLabel jLabelItemLevel;
    private javax.swing.JLabel jLabelItemName;
    private javax.swing.JLabel jLabelItemTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JPanel jPanelItemImage;
    private javax.swing.JProgressBar jProgressBarExperience;
    private javax.swing.JProgressBar jProgressBarHealth;
    private javax.swing.JTextField jTextFieldCharacterLevel;
    private javax.swing.JTextField jTextFieldCharacterName;
    private javax.swing.JTextField jTextFieldCharacterSpeed;
    private javax.swing.JTextField jTextFieldItemDamage;
    private javax.swing.JTextField jTextFieldItemLevel;
    private javax.swing.JTextField jTextFieldItemName;
    private javax.swing.JButton jbuttonSalir;
    private javax.swing.JLabel jlabelCharacterEXP;
    private javax.swing.JPanel screenBoard;
    // End of variables declaration//GEN-END:variables
}
